# Generated by Django 2.0.7 on 2018-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=None)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=2000)),
                ('charity', models.CharField(max_length=100)),
            ],
        ),
    ]
