# Generated by Django 2.0.7 on 2018-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
