# Generated by Django 2.0.7 on 2018-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180808_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='charity_percent',
            field=models.IntegerField(max_length=100),
        ),
    ]
