# Generated by Django 2.0.7 on 2018-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180808_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='charity_percent',
            field=models.IntegerField(default=0),
        ),
    ]
