# Generated by Django 2.0.7 on 2018-08-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180809_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='userId',
        ),
        migrations.AddField(
            model_name='charity',
            name='progress_bar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='total_money_raised',
            field=models.IntegerField(default=0),
        ),
    ]
