# Generated by Django 2.0.7 on 2018-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180810_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='progress_bar',
        ),
        migrations.AddField(
            model_name='charity',
            name='mission_statement',
            field=models.CharField(default='filling space', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='name',
            field=models.CharField(default='filling space', max_length=100),
            preserve_default=False,
        ),
    ]
